name: Publish
on:
  release:
    types:
      - published
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Configure AWS Credentials (prod)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.MPRO_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MPRO_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Publish
        run: ./.github/publish.sh
