name: Publish
on:
  release:
    types:
      - published
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, macOS-11]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  deploy:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Get wheels
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PUBLISHER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLISHER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Publish
        run: ./.github/publish.sh
